name: Build and Release
run-name: ${{ github.actor }} is releasing new spread pool results
on:
  workflow_dispatch:    
  push:
    branches: 
      - main
  schedule:
    # Thursday 11:45pm = Friday 4:45am
    # Sunday 11:45am, 3:45pm = Sunday 4:45pm, 8:45pm
    # Sunday 7:45pm, 11:45pm = Monday 12:45, 4:45am
    # Monday 11:45pm = Tuesday 4:45am
    - cron: '45 0,4 * * 1,2,5'
    - cron: '45 16,20 * * 0'
jobs:
  build-and-release:
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy to Github
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site
          publish_branch: gh_pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
