name: Test PR Build
on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Start server and test pages
        run: |
          # Start http-server in the background
          npx http-server _site -p 8080 &
          SERVER_PID=$!
          
          # Wait for server to start and verify it's running
          echo "Waiting for server to start..."
          sleep 5
          
          if ! ps -p $SERVER_PID > /dev/null; then
            echo "✗ ERROR: Server failed to start"
            exit 1
          fi
          echo "✓ Server started successfully (PID: $SERVER_PID)"
          
          # The build uses --pathprefix=jimbos-nfl-pool, so pages are under that path
          BASE_URL="http://localhost:8080/jimbos-nfl-pool"
          
          # Test homepage
          echo ""
          echo "Testing homepage..."
          if curl -f -s "$BASE_URL/" > /dev/null; then
            echo "✓ Homepage loaded successfully"
          else
            echo "✗ ERROR: Homepage failed to load"
            kill $SERVER_PID || true
            exit 1
          fi
          
          # Test year standings pages (new URL scheme includes years)
          echo ""
          echo "Testing year standings pages..."
          YEARS_FOUND=0
          for year in 2024 2025; do
            if curl -f -s "$BASE_URL/$year/" > /dev/null 2>&1; then
              echo "✓ Year $year standings page loaded successfully"
              YEARS_FOUND=$((YEARS_FOUND + 1))
            fi
          done
          
          if [ $YEARS_FOUND -eq 0 ]; then
            echo "⚠ WARNING: No year standings pages found"
          else
            echo "Found $YEARS_FOUND year standings pages"
          fi
          
          # Test spread pool week pages with year-based URLs (new URL scheme: /YEAR/week/WEEK/)
          echo ""
          echo "Testing spread pool week pages..."
          WEEKS_FOUND=0
          
          # Test 2024 weeks
          for week in 1 4 5 6; do
            if curl -f -s "$BASE_URL/2024/week/$week/" > /dev/null 2>&1; then
              echo "✓ 2024 Week $week page loaded successfully"
              WEEKS_FOUND=$((WEEKS_FOUND + 1))
            fi
          done
          
          # Test 2025 weeks
          for week in 6 7 8; do
            if curl -f -s "$BASE_URL/2025/week/$week/" > /dev/null 2>&1; then
              echo "✓ 2025 Week $week page loaded successfully"
              WEEKS_FOUND=$((WEEKS_FOUND + 1))
            fi
          done
          
          if [ $WEEKS_FOUND -eq 0 ]; then
            echo "✗ ERROR: No week pages found!"
            kill $SERVER_PID || true
            exit 1
          fi
          echo "Found $WEEKS_FOUND week pages"
          
          # Test player pages (sample a few common names from the data)
          echo ""
          echo "Testing player pages..."
          PLAYERS_FOUND=0
          for player in "ken" "cosmo" "aaron" "ryan"; do
            if curl -f -s "$BASE_URL/players/$player/" > /dev/null 2>&1; then
              echo "✓ Player page for '$player' loaded successfully"
              PLAYERS_FOUND=$((PLAYERS_FOUND + 1))
            fi
          done
          
          if [ $PLAYERS_FOUND -eq 0 ]; then
            echo "⚠ WARNING: No player pages found (this may be expected if player data structure changed)"
          else
            echo "Found $PLAYERS_FOUND player pages"
          fi
          
          echo ""
          echo "✓ All required tests passed!"
          
          # Cleanup
          echo ""
          echo "Stopping server..."
          kill $SERVER_PID 2>/dev/null || true
